defaults: &defaults

development:
  <<: *defaults
  isCounter:
    - true
    - false
  currentStatus:
    - ONLINE
    - OFFLINE
    - FAULT
    - PAUSE
    - STOP
    - WORKING
  functionCode:
  workorderNo:
    - test1
    - test2
    - test3
    - test4
    - test5
    - test6
    - test7
